### PR TITLE
Allow webui to be accessible in the host when in development

### PR DESCRIPTION
**Pull request by zkanda**
As the title says. :)

### CODE REVIEW

**Comment by gittycat** [comment]
I'm curious. What's the point of this PR since we can easily override CMD from the `docker run` command or from a docker compose file?

**Comment by zkanda** [comment]
True, this can be solve via documentation I guess, in the `Running Consul for Development` on docker hub page, I was expecting I can access the webui directly just by running `docker run -d --name=dev-consul consul`, but I couldn't, I still have to find how to do that and was a bit frustrated, hence this PR. Of course, if your an expert on consul, I guess you don't really need this.

**Comment by marten** [comment]
:+1: for either of these solutions, but I'd suggest this PR. I couldn't actually reach the web UI after following the README, and got pretty confused.

**Comment by mknecht** [comment]
I agree with @marten . The code comment in the Dockerfile says: “exposes a web UI” … that's not really true, if you can't access it conveniently.

**Comment by kortatu** [comment]
+1

**Comment by slackpad** [comment]
Thanks! Sorry for the delay in merging this one.

**Pull request merged**
