### PR TITLE
Allow Consul to run as non-root user

### PR DESCRIPTION
**Pull request by chrisbsmith**
Submitting a PR on behalf of @DatzAtWork.  Running as non-root is necessary for other environments, specifically OpenShift.

chown /consul/config and /consul/data is only possible consul is started with root. No all environments allow to start Docker containers as root. If it was started with uid 100 (consul) the chown fails and must be skipped.

### CODE REVIEW

**Comment by mkeeler** [comment]
@chrisbsmith I assume then that you run the container as the given user and already have set permissions for the config/data accordingly to make this work.

**Comment by chrisbsmith** [comment]
@mkeeler I'm running the container as is from the PR.  Using a statefulset that maps in a persistent volume to data/config but I don't change the permissions afterwards.  The issue doesn't appear to be with ownership of the folders, rather with the ability to run `chown` as a non-root user

**Comment by DatzAtWork** [comment]
> rather with the ability to run `chown` as a non-root use

Right!

**Comment by pazovtsev** [comment]
@DatzAtWork Pls, merge pool request

**Comment by DatzAtWork** [comment]
> 
> 
> @DatzAtWork Pls, merge pool request

I have no permissions to merge

**Comment by patvong** [comment]
@alvin-huang @mkeeler Any way to look into merging this? We have the same issue and we'd like to avoid forking to our own repo to be able to run docker-consul as non-root.

**Comment by AlexisLessard** [comment]
We would like to have it merged too. The only way for us to make the image work so far is to run `oc adm policy add-scc-to-user anyuid -z default`, but it is not advisable in production, as it allows to run any container as root, which would open a plethora of vulnerabilities. The image should be able to work securely without modifications from an administrator.

**Comment by MartinHeinz** [comment]
Could this be merged, please? As other people mentioned, I would too like to avoid forking or using some ad-hoc solution. There really is nothing preventing the merge...

**Comment by mkeeler** [comment]
I apologize for not closing this one a while ago. We ended up with an alternative solution for the same thing which is to allow setting an env var `CONSUL_DISABLE_PERM_MGMT` to completely disable the user/permission management that the entrypoint script does.

When set (to any non-empty string value), this disables the `chown`, `setcap` and `su-exec` operations that exist towards the end of the entrypoint script.

The env var is desirable as it doesn't change behavior for any existing users as opposed to just checking if we are not uid 0 and assuming that the desirable behavior is to just not do any of that.

**Comment by alexlaverty** [comment]
@mkeeler what version was this fix merged into?

**Comment by mkeeler** [comment]
@alexlaverty This was added to the v1.5.2 docker image

**Pull request closed without merging**
