### PR TITLE
Add multiarch support based on available release binaries

### LINKED ISSUE #67: Multi-arch docker images for consul
Hi, I'm looking to enable docker containers for packages like consul for multiple architectures on dockerhub, starting off with a focus on ppc64le. Wanted to check on the work that will be involved to do that

I have locally been able to successfully test ppc64le changes to the dockerfiles in this repo - changes for enabling additional arch would be minimum.

The official images have this method for enabling multi-arch : https://github.com/docker-library/official-images#multiple-architectures, as mentioned there they recommend having a single dockerfile with swithches for arch-specific changes, want to understand if ppc64le additions would be accepted to the dockerfile here (can raise a PR) and if the ppc64le image creation process can be initiated subsequently under docker-library/official-images (would mostly need changes to the metadata file https://github.com/docker-library/official-images/blob/master/library/consul)

Thanks!

### PR DESCRIPTION
**Pull request by tianon**
Fixes #67

@slackpad any idea what the value of `GOARM` was when building the `consul_1.0.3_linux_arm.zip` binary that's on https://releases.hashicorp.com/consul/1.0.3/ ?

(or anyone with an `arm32v6` Raspberry Pi 1 or Zero willing to try running that binary for me and tell me if it errors?)

### CODE REVIEW

**Comment by tianon** [comment]
Just FYI, the next step if this is acceptable to merge would be to update https://github.com/docker-library/official-images/blob/master/library/consul to use the new RFC 2822 format so it can include an `Architectures` header, something like:

```
Maintainers: James Phillips <james@hashicorp.com> (@slackpad)
GitFetch: refs/heads/*

Tags: 1.0.3, latest
Architectures: amd64, i386, arm64v8
GitRepo: https://github.com/hashicorp/docker-consul.git
GitCommit: deadbeefdeadbeefdeadbeefdeadbeef
Directory: 0.X
```

I have successfully built and run this on `arm64v8`, going to test `i386` now (which is arguably the easier one to test :innocent:).

**Comment by tianon** [comment]
Now tested successfully on `i386`, and added `consul version` in the `RUN` line as a tiny smoke test to ensure the binary we download does successfully run on the architecture upon which we're building (which isn't much but it's unobtrusive and is _something_).

**Comment by seffyroff** [comment]
> (or anyone with an arm32v6 Raspberry Pi 1 or Zero willing to try running that binary for me and tell me if it errors?)
@tianon 
`HypriotOS/armv6: seffyroff@cottagepi in ~/dev
$ ls -l
total 50280
-rwxr-xr-x 1 seffyroff seffyroff 41185806 Jan 24 15:07 consul
-rw-r--r-- 1 seffyroff seffyroff 10284141 Jan 24 07:16 consul_1.0.3_linux_arm.zip
-rw------- 1 seffyroff seffyroff       36 Feb 17 09:59 node-id
drwxr-xr-x 3 seffyroff seffyroff     4096 Feb 17 09:59 raft
drwxr-xr-x 2 seffyroff seffyroff     4096 Feb 17 09:59 serf
HypriotOS/armv6: seffyroff@cottagepi in ~/dev
$ ./consul agent -server -bind=127.0.0.1 -data-dir=./
==> Starting Consul agent...
==> Consul agent running!
           Version: 'v1.0.3'
           Node ID: 'd92cf95a-5055-fefc-ed72-26a996f3c460'
         Node name: 'cottagepi'
        Datacenter: 'dc1' (Segment: '<all>')
            Server: true (Bootstrap: false)
       Client Addr: [127.0.0.1] (HTTP: 8500, HTTPS: -1, DNS: 8600)
      Cluster Addr: 127.0.0.1 (LAN: 8301, WAN: 8302)
           Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false

==> Log data will now stream in as it occurs:

    2018/02/17 10:00:17 [INFO] raft: Initial configuration (index=0): []
    2018/02/17 10:00:17 [INFO] raft: Node at 127.0.0.1:8300 [Follower] entering Follower state (Leader: "")
    2018/02/17 10:00:17 [INFO] serf: EventMemberJoin: cottagepi.dc1 127.0.0.1
    2018/02/17 10:00:17 [WARN] serf: Failed to re-join any previously known node
    2018/02/17 10:00:17 [INFO] serf: EventMemberJoin: cottagepi 127.0.0.1
    2018/02/17 10:00:17 [INFO] agent: Started DNS server 127.0.0.1:8600 (udp)
    2018/02/17 10:00:17 [WARN] serf: Failed to re-join any previously known node
    2018/02/17 10:00:17 [INFO] consul: Adding LAN server cottagepi (Addr: tcp/127.0.0.1:8300) (DC: dc1)
    2018/02/17 10:00:17 [INFO] consul: Handled member-join event for server "cottagepi.dc1" in area "wan"
    2018/02/17 10:00:17 [INFO] agent: Started DNS server 127.0.0.1:8600 (tcp)
    2018/02/17 10:00:17 [INFO] agent: Started HTTP server on 127.0.0.1:8500 (tcp)
    2018/02/17 10:00:17 [INFO] agent: started state syncer
`
Looks good :)

**Comment by tianon** [comment]
Updated, thanks @seffyroff! :+1:

**Comment by sudhagarc** [comment]
Can we merge this to master, please?

**Comment by maxaalderink** [comment]
I would very much appreciate it if the official Consul docker image was multi-arch so please merge this to master.

**Comment by tianon** [comment]
@slackpad anything I can adjust about this to make it acceptable? :innocent: :heart:

**Comment by slackpad** [comment]
Unfortunately I'm no longer with HashiCorp so can't commit this. I'll cc @pearkes to route this to another HashiCorp person for you.

**Comment by tianon** [comment]
(I wish I could :heart: emoji react to your comment more than once -- sad to see you've moved on, and appreciate your help/maintenance and hope our paths intersect again someday! :heart:)

**Comment by slackpad** [comment]
Thanks for the kind words @tianon - totally appreciate that! It has been awesome working with you getting the Consul image off the ground and keeping it current. Thanks for steering me away from some weird approaches back in the early days when I was feeling out how to do this :-)

**Comment by pearkes** [comment]
Sorry for the delay on this, folks!

**Pull request merged**
