### PR TITLE
bump version to 0.8.1

### PR DESCRIPTION
**Pull request by davidkarlsen**
This change is [Reviewable](https://reviewable.io/reviews/hashicorp/docker-consul/58)

### CODE REVIEW

**Comment by slackpad** [comment]
Hi @davidkarlsen thanks for the PR - sorry I didn't see this and already committed it in https://github.com/hashicorp/docker-consul/commit/ab9d553087fffb25ebabb41c38e5cea3deef1019.

**Comment by davidkarlsen** [comment]
No prob - still waiting for the build to appear on docker hub though.

**Comment by slackpad** [comment]
The Docker Hub update will happen once https://github.com/docker-library/official-images/pull/2866 is merged.

**Comment by davidkarlsen** [comment]
@slackpad When/who does that?

**Comment by slackpad** [comment]
Docker folks do - they did this morning and the build is up now on Docker hub.

**Pull request closed without merging**
