### PR TITLE
Optional short hostname as default node name

### PR DESCRIPTION
**Pull request by marcuslinke**
Added option for passing CONSUL_NODE_NAME.

If CONSUL_NODE_NAME is not configured and `CONSUL_SHORT_DEFAULT_NODE_NAME=true` the short hostname will be used as node name by default. 

This is useful in swarm environments where consul is deployed as global service and specific node name can't be configured. To make use of consuls dns capabilities in this case fqdn node names must be avoided (or better: short node names must be forced).

Also  adds CONSUL_CLIENT_ADDRESS option to allow client ip `0.0.0.0` for example.

@slackpad Please review. Thanks!

### CODE REVIEW

**Comment by mkeeler** [comment]
@marcuslinke What is the use case for this? In particular we have a CONSUL_LOCAL_CONFIG env var which can be set and will be dropped into the configuration directory as normal json configuration. In that way you can configured whatever extra items you need including the client addr and the node name. 

I would be hesitant to bring in more complexity and environment handling into the entrypoint script when what you want can just be handled via what is already there.

**Comment by stepan-romankov** [comment]
Hi, @mkeeler 

Could you please advise how to set Consul node name via CONSUL_LOCAL_CONFIG?
{"node": "xxx"} seems not working.

**Comment by mkeeler** [comment]
We haven't heard back in a while so I am going to close this for now. If you have a use case where using the CONSUL_LOCAL_CONFIG to pass configuration including the node name or putting it within a configuration in /consul/config doesn't work I can reopen this.

**Comment by dekimsey** [comment]
@mkeeler I was just looking for this functionality myself. When running the container in these environments the CONSUL_LOCAL_CONFIG is going to be identical for all instances of the service. We do not know at runtime what the instance ID. 

Consul's docs recommend not using `.` in node names as it creates entries that aren't discoverable by DNS (it even warns about this), but it also doesn't have an option or behavior to tell it to use a short-hostname when auto-selecting the node name. One could argue this behavior ought to be a configuration option in Consul and not the Dockerfile.

In my case we may end up having to wrap the consul container's bootstrap so that we can set a better hostname and include some ECS-level metadata into the node-meta (like the task and instance ID). Though I also wouldn't mind seeing a consul level behavior to auto-add some node-meta entries based on EC2 metadata or the like. I think that's hugely out of scope though :).

**Comment by mkeeler** [comment]
@dekimsey I think that makes a lot of sense. I looked into what it would take to implement this behavior in Consul instead of the entrypoint script. However it appears that Go doesn't have the ability to retrieve a short hostname so it would be difficult.

I took a second look at this PR but the main reason I cannot merge it right now is that it unconditionally sets a node name. Because it is set on the command line and not in a configuration file it would be impossible to override. So we would need a way to indicate that a node name should be set and then secondly what it should be set to or how to calculate it.

**Comment by dekimsey** [comment]
@mkeeler the notion of a short-name appears to be as trivial as [just splitting the nodename](https://sources.debian.org/src/hostname/3.23/hostname.c/#L269) on periods and taking the first item. The kernel doesn't seem to be much going on in [uname](https://linux.die.net/man/2/uname) about the notion of a short-name either.

**Comment by mkeeler** [comment]
I had started going to look at the hostname command in gnu coreutils but I ended up thinking I was looking at the wrong code as the source I found didn't even support the `-s`.

If its as simple as splitting on the `.` and taking the first part then I think this would be better implemented in Consul.

**Pull request closed without merging**
